spring:
  application:
    name: configuration-microservice
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShivaTechie/ecom-config

#eureka:
#  instance:
#    hostname: configuration-microservice
#  client:
#    registryFetchIntervalSeconds: 1
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
      
server:
  port: 8888